### ISSUE TITLE
[BUG] [v0.0.3] Crashes on dedicated servers

### ISSUE THREAD

**Issue by TigerWalts** [AMPZNetwork/All-The-Forge-7#1]
**Describe the bug**
2 mods in the pack are not compatible with dedicated servers
- Baubles Reborn 1.9.0.1-1.17.1
- SimplyJetpacks 1.17.1-2.7.2.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Forge server
2. Remove/disable the client-only mods:
  - Controlling
  - Ding
  - OptiFine
  - FancyMenu
  - Hidden Recipe Book
  - Konkrete
  - Baubles Interface

**Expected behaviour**
Server to start up

**Crash Log**
Already reported to the mod authors:
- https://github.com/lazyMods/baubles/issues/18
  Fixed for 1.18.1, but mod author will not fix for 1.17.1
- https://github.com/Tomson124/SimplyJetpacks2/issues/58
  Issue is closed but the bug has not been fixed

**Basic Information (please complete the following information):**
 - OS: Win 10/Ubuntu 
 - All The Forge 7 Version: 0.0.3
 - Platform: N/A
 - Extra mods added by you: N/A

**Comment by LabsZero** [comment]
Thank you for reporting this issue. I will look into a fix.
